include config

all:
ifeq ($(CONFIG_NEL_A), y)
	@echo "CONFIG_NEL_A is $(CONFIG_NEL_A)"
else
	@echo "CONFIG_NEL_A is not $(CONFIG_NEL_A)"
endif
ifeq ($(CONFIG_NEL_B), Nelson)
	@echo "CONFIG_NEL_B is $(CONFIG_NEL_B)"
else
	@echo "CONFIG_NEL_B is not $(CONFIG_NEL_B)"
endif
ifeq ($(CONFIG_NEL_B), "Nelson")
	@echo "CONFIG_NEL_B is $(CONFIG_NEL_B)"
else
	@echo "CONFIG_NEL_B is not $(CONFIG_NEL_B)"
endif
